root = "../../"
testdata_dir = "testdata"
tmp_dir = "/tmp"

[build]
  args_bin = []
  cmd = "go build -o /tmp/backendmain *.go"
  bin = "/tmp/backendmain"

  delay = 1000
  exclude_dir = ["assets", "testdata", "tmp", "cli", "vendors", "/app/web/views/node_modules"]
  exclude_file = []
  exclude_regex = ["_test.go"]
  exclude_unchanged = false
  follow_symlink = false
  full_bin = ""
  include_dir = ["locallinks", "services", "gen", "datastore", "cmd", "clients", "web"]
  include_ext = ["go", "tpl", "tmpl", "html"]
  include_file = []
  kill_delay = "0s"
  log = "build-errors.log"
  poll = true
  poll_interval = 2000
  rerun = false
  rerun_delay = 500
  send_interrupt = false
  stop_on_error = false

[color]
  app = ""
  build = "yellow"
  main = "magenta"
  runner = "green"
  watcher = "cyan"

[log]
  main_only = false
  time = false

[misc]
  clean_on_exit = true

[screen]
  clear_on_rebuild = false
  keep_scroll = true
